
const PROXY_PATH_REGEX = new RegExp(/([a-z]+)\|(.*)/)
const SOCKET_PROXIED_RESPONSE = "res";
const SOCKET_PROXIED_REQUEST_CLOSE = "close";
export {
	PROXY_PATH_REGEX,
	SOCKET_PROXIED_RESPONSE,
	SOCKET_PROXIED_REQUEST_CLOSE
}